[build]
  publish = "public/"
  command = "node_modules/.bin/gulp build:preview"

[build.environment]
  NODE_VERSION = "8"
  ALGOLIA_APP_ID = "NI1G57N08Q"
  ALGOLIA_API_KEY = "d3eff3e8bcc0860b8ceae87360a47d54"
  ALGOLIA_INDEX_NAME = "prod_docs_couchbase"

[context.deploy-preview]
  command = "node_modules/.bin/gulp build:preview pack"

[[headers]]
  for = "/_/font/*"
  [headers.values]
    Cache-Control = "public,max-age=604800"
